### ISSUE TITLE
Add "Disconnect Server" button?

### ISSUE THREAD

**Issue by tjvandam** [SmartParksOrg/smartparks-connect-web#14]
Not sure if this helps, but for users this may make sense.

**Comment by krasi-georgiev** [comment]
what would this button do?

**Comment by tjvandam** [comment]
Disconnect the gRPC connection.

**Comment by krasi-georgiev** [comment]
the grpc is not connected it just sends single requests to it.

**Comment by krasi-georgiev** [comment]
fee free to re-open if you had something else in mind
