### ISSUE TITLE
Add connection to RockBLOCK Api to send messages

### ISSUE THREAD

**Issue by tjvandam** [SmartParksOrg/smartparks-connect-web#15]
Now we are only able to connect to Chirpstack v3 servers to send downlinks. In the near feature we also need to be able to do the same but then via the RockBLOCK Iridium Application. This way the messages to the device will be send over Iridium satellite and not over LoRaWAN. 

API docs: 
- https://docs.rockblock.rock7.com/docs/integration-with-application
- https://docs.rockblock.rock7.com/reference/testinput --> this includes GO example and test template!

For this we need to make a seperate connection module, but it should be able to use the same device template. Only the way it sends the payload probably will look a bit different in format.

Maybe add a "hamburger menu" so the user can switch between LoRaWAN and Iridium module.

**Comment by krasi-georgiev** [comment]
@tjvandam I am thinking to add more sub-tabs under the `Connect Server Form` tab to allow switching to the type of server to connect. What do you think?
If you have a different idea, please show some draft image with explanations

**Comment by tjvandam** [comment]
@krasi-georgiev Maybe it is better to make a more clear difference between LoRaWAN connection (API) and in this case RockBLOCK (Iridium) on a higher level. So maybe this logic should be "above" these tabs. So first the user selects the "mode" of connection and thene the existing forms will do the rest.

**Comment by krasi-georgiev** [comment]
one key difference is that Server address to chirpstack is grpc where RockBLOCK uses HTTP so can't use the same form fields as they refer to grpc and do a different validation

**Comment by tjvandam** [comment]
Yes, so it is probably better to make it a separate section. Maybe even use Hamburger menu to switch between different sections?
