### ISSUE TITLE
Add hamburger menu with About section

### ISSUE THREAD

**Issue by tjvandam** [SmartParksOrg/smartparks-connect-web#20]
This will allow us to give credits to the developers and link to the appropriate sources for more information.

Best is to look at the Smart Parks Connect App for an example.
https://play.google.com/store/apps/details?id=com.smartparks_connect_app&hl=en_US&gl=US

**Comment by krasi-georgiev** [comment]
added in https://github.com/SmartParksOrg/smartparks-connect-web/commit/464427d273513f6e6450c2e1d5788a629da877b7
