### ISSUE TITLE
Format "Request Records"

### ISSUE THREAD

**Issue by tjvandam** [SmartParksOrg/smartparks-connect-web#22]
Change:
- dateTime --> Date + Time in human readable format, maybe even use moment to display since on recent values.
- DeviceID --> Device EUI
- Payload --> Payload (hex)
- Base64 --> Payload (base64)

Add:
- Device Name --> example SP05004
- FPort --> 3 or 32
- Type --> settings or commands
- Confirmed --> if true "confirmed" if false "unconfirmed"

**Comment by krasi-georgiev** [comment]
done
